import { Card } from '@/models/card'
import { Deck } from '@/models/deck'
import { ICard, ICardConstructorOptions } from '@/models/types'
import { probabilityByRarity } from './probability-by-rarity'

const DECK: ICardConstructorOptions[] = [
  // truth
  {
    value:
      'Истината трябва да излезе на яве! {{randomPlayer}} трябва да те попита нещо.',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кой ти беше първата бройка?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Какво е нещо, което не искаш родителите ти да знаят?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Какво е нещото, за което само няколко хора знаят?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Коя е най-голямата лъжа, която си казвал?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кога плака за последно?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'С коя звезда би спал?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кой ти е най-лошият навик?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кога си бил най-мега пиян? Какво стана?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кога те е било най-много срам?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Кое е най-гнусното нещо, което си правил?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Разкажи си за първата целувка.',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Пърдял ли си в неподходящо време? Кога?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Какво мислиш за бездомните безработни хора?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Нарушавал ли си закона? Кога? Как?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Коя ти е най-гадната среща?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Коя ти е най-хубавата среща?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Лъгал ли си, за да се измъкнеш от гадна среща?',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Пикал ли си в басейн, гнусар...',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Срал ли си в басейн, гнусар...',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Срал ли си в гората, гнусар...',
    rarity: 'COMMON',
    type: 'TRUTH',
    author: undefined,
    points: 1,
  },
  {
    value: 'Признай какво да възбужда най-много.',
    rarity: 'UNCOMMON',
    type: 'TRUTH',
    author: undefined,
    points: 2,
  },
  {
    value: 'Какъв е твоя фетиш?',
    rarity: 'UNCOMMON',
    type: 'TRUTH',
    author: undefined,
    points: 2,
  },
  {
    value: 'Признай какво да възбужда най-много в {{randomPlayer}}.',
    rarity: 'UNCOMMON',
    type: 'TRUTH',
    author: undefined,
    points: 2,
  },
  {
    value: 'Присъствал ли си, когато някой друг около теб е правил секс?',
    rarity: 'UNCOMMON',
    type: 'TRUTH',
    author: undefined,
    points: 2,
  },
  {
    value: 'Кое е най-мръсното и неморално нещо, което те възбужда?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'С кого си искал да спиш от 8-ми до 12-ти клас?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Ако можеше да спиш с {{randomPlayer}}, щеше ли?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Разкажи неловка история от детството си.',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Кога го прави за последно? Къде? Как? Колко време?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Кое е най-странното място където си го правил?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Кога, как и с кого е най-гадното ти сексуално преживяване?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Правил ли си "Мушкато и Бегония"',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Какво е най-дразнещото в {{randomPlayer}}',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Правил ли си стрийптийз за своя партньор?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Кой би целунал в стаята си с изключение на партньора си.',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value: 'Бързо и яростно ли го предпочиташ или бавно и нежно?',
    rarity: 'RARE',
    type: 'TRUTH',
    author: 'Доби',
    points: 3,
  },
  {
    value:
      'Ако сме в зомби апокалипсис и видиш някво супер секси зомби заклещено в пералнята... би ли? Не е много изгнило.',
    rarity: 'RARE',
    type: 'TRUTH',
    author: undefined,
    points: 3,
  },
  {
    value:
      'Тялото ти правило ли е скрийншот? (експорт на телесни течности от горе и отдолу едновременно)',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value: 'Кажи сега... Коя е най-странната поза в която си го правил?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value: 'Кажи сега... Кога се насра за последно?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value: 'Кажи сега... Записвал ли си домашно порно?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: 'Доби',
    points: 5,
  },
  {
    value: 'Правил/а ли си го в задния вход?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value: 'Ял ли си гъз?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value: 'Правил ли си джиджи-биджи с повече от един човек едновременно?',
    rarity: 'EPIC',
    type: 'TRUTH',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Kiss, Marry, Kill с майка ти, баба ти и прабаба ти/ баща ти, дядо ти и прадядо ти.',
    rarity: 'LEGENDARY',
    type: 'TRUTH',
    author: undefined,
    points: 7,
  },
  //   Dare
  {
    value: 'Татуирай с химикал/маркер върху ръката си дума с 3 букви.',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Дръпни си вежите с тиксо и стой така 2 рунда.',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Легни на пода и се престори на пържещ се бекон.',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Легни на пода и се престори на пържещ се бекон.',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Гризни суров картоф. Дъвчи малко, пък ако ти хареса си го дояж...',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Завърти се 10 пъти и се пробвай да ходиш в права линия.',
    rarity: 'COMMON',
    type: 'DARE',
    author: undefined,
    points: 1,
  },
  {
    value: 'Натъпчи си устата с храна и стой така 2 хода.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: '{{randomPlayer}} трябва да те гъделичка за 6 секунди.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Татуирай с химикал/маркер върху ръката си дума с 3 букви.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Помириши мишницата на {{randomPlayer}} и опиши на какво мирише.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Направи личен комплимент на всеки един играч.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Сложи си чифт бельо като шапка. Препоръчително е да е твое.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Оближи си големия пръст на крака.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value:
      'Завържи си очите. {{randomPlayer}} трябва да ти сложи нещо в устата. ХРАНА бе мръсник...',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Имитирай някого от играчите, докато нев бъде познат от групата.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Топни си краченцето в тоалетната.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Направи супер крива физиономия и я дръж за един рунд.',
    rarity: 'UNCOMMON',
    type: 'DARE',
    author: undefined,
    points: 2,
  },
  {
    value: 'Снимай се супер криндж и си смени профилната снимка.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value:
      '{{randomPlayer}} трябва да ти пусне кубче лед на врата/във сутиена.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Имитирай всички движения на {{randomPlayer}} за 1 рунд.',
    rarity: 'RARE',
    type: 'DARE',
    author: 'Доби',
    points: 3,
  },
  {
    value:
      'Започни история с едно изречение. Следващият по ход да продължи и така докато всички на са добавили нещо към историята.',
    rarity: 'RARE',
    type: 'DARE',
    author: 'Доби',
    points: 3,
  },
  {
    value: 'Коментирай стара снимка на {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'DARE',
    author: 'Доби',
    points: 3,
  },
  {
    value: 'Изшепни нещо мръсно на {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'DARE',
    author: 'Доби',
    points: 3,
  },
  {
    value:
      'Изяж една супена лъжица от най-гадния сос в помещението. При липса използвай олио/оцет/зехтин.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Оближи дръжка на врата. После дезинфекция.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Изпей серенада на {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value:
      'Обърни си всички дрехи наопаки. Сутиените и гащите също. Стой така поне 2 рунда.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Смени си дрехите с {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value:
      'Изкарай вътрешния си актьор и влез в дълбок спор със стената. Ако не те слуша я набий.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Махни си чорапите със зъби.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Завържи очите на {{randomPlayer}} и му дай да целуне 3 предмета.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value: 'Отиди отвън и откъсни точно 22 стръка трева с пинцети.',
    rarity: 'RARE',
    type: 'DARE',
    author: undefined,
    points: 3,
  },
  {
    value:
      'Нека {{randomPlayer}} залепи тиксо/коламаска на рандъм част от тялото ти и след това да го дръпне с всичка сила. При липса може просто да ти шибне един шамар.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Момче: {{randomPlayer}} да ти направи маникюр на едната ръка; Момиче: {{randomPlayer}} да ти нарисува веждите.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Обади се на майка си и кажи, че не можеш да си намериш гадже с много паникьосан глас. Може и друг роднина ако майка ти ще те набие.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Излез отвън и се престори, че косиш ливадата с невидима косачка, която не можеш да удържиш.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Помириши краката на всеки играч и ги сортирай от най-вонящи до най-свежи.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Прошепни нещо на {{randomPlayer}}. Трябва да го накраш да се изчерви.',
    rarity: 'EPIC',
    type: 'DARE',
    author: 'Доби',
    points: 5,
  },
  {
    value: 'Бъркай в кофата и казвай на глас всичко, което хванеш.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value: 'Целуни гума на кола.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value: 'Измисли правило, което всички да спазват до края на играта.',
    rarity: 'EPIC',
    type: 'DARE',
    author: 'Доби',
    points: 5,
  },
  {
    value: 'Пусни възрастен филм по твое желание. Да звучи за фон един рунд.',
    rarity: 'EPIC',
    type: 'DARE',
    author: 'Доби',
    points: 5,
  },
  {
    value: '{{randomPlayer}} трябва да ти нарисува нещо с червило на корема.',
    rarity: 'EPIC',
    type: 'DARE',
    author: 'Доби',
    points: 4,
  },
  {
    value:
      '{{randomPlayer}} трябва да си свали чорапите и ти да ги носиш като ръкавици. Само ако няма гъбички.',
    rarity: 'EPIC',
    type: 'DARE',
    author: undefined,
    points: 4,
  },
  {
    value:
      'Пусни лайв във фейсбук. Взиеми някакъв продукт и започни да четеш етикета със съставките на друг език.',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 7,
  },
  {
    value: 'Излез на двора и се изкрещи "МАМКА МУ, ОСИНОВЕН СЪМ".',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 7,
  },
  {
    value:
      'Снимай се с тоалетната чиния и качи снимка в соц. мрежите с надпис "Дамата/кавалера ми за вечерта."',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 6,
  },
  {
    value:
      'Дай на {{randomPlayer}} да ти прочете браузърната история на глас за 1 минута.',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 6,
  },
  {
    value: 'Скочи в казан.',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 9,
  },
  {
    value:
      'Оплачи се на майката на партньора си, че партньорът ти не иска да го любиш. Ако нямаш партньор - на приятел на бившия/бившата.',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 9,
  },
  {
    value: '{{randomPlayer}} трябва да ти сцепи яйце в главата.',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Напиши на бившето с гадже: "Все още си мисля за теб нощем преди да заспя."',
    rarity: 'LEGENDARY',
    type: 'DARE',
    author: undefined,
    points: 10,
  },
  //  DARE
  {
    value: 'Наздраве! Отпий една глътка от питието си.',
    rarity: 'COMMON',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value: 'Дай си наздраве на {{randomPlayer}}. Пийте по една голяма глътка.',
    rarity: 'COMMON',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Изпий голям гълток от питието си. Ако нямаш питие ще трябва да си сипеш или да крадеш.',
    rarity: 'COMMON',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Пийни си една глътка от чашата на друг играч. Приоритет имат напитки различни от твоята с по-висок спиртен градус.',
    rarity: 'COMMON',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Изпий един шот със сок от кисели краставици/оцет/лимонов сок (нещо кисело).',
    rarity: 'UNCOMMON',
    type: 'DRINK',
    author: undefined,
    points: 2,
  },
  {
    value:
      'Пий без разредител до края на играта. Ако пиеш глезотии пий по 3 глътки. Ако вече си изтеглил тази карта си изпий чашата до край.',
    rarity: 'RARE',
    type: 'DRINK',
    author: undefined,
    points: 2,
  },
  {
    value: 'Изпий една глътка от пиенето на {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'DRINK',
    author: undefined,
    points: 3,
  },
  {
    value: 'Смени пиенето за 2 рунда.',
    rarity: 'RARE',
    type: 'DRINK',
    author: undefined,
    points: 3,
  },
  {
    value: 'Бомбок! Направи по един шот на всички и го изпийте. (20мл)',
    rarity: 'EPIC',
    type: 'DRINK',
    author: undefined,
    points: 2,
  },
  {
    value:
      'Измисли прякор на {{randomPlayer}} и всеки трябва да го използва до края на играта. Който го забрави - пие.',
    rarity: 'EPIC',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Измисли прякор на {{randomPlayer}} и всеки трябва да го използва до края на играта. Който го забрави - пие.',
    rarity: 'EPIC',
    type: 'DRINK',
    author: 'Доби',
    points: 1,
  },
  {
    value:
      'Групово предизвикателсво! Ти избираш пиенето и всички пият по един шот. (20мл)',
    rarity: 'EPIC',
    type: 'DRINK',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Играете на "Никога не съм". Казваш 5 неща и всеки, който ги е правил трябва да пие.',
    rarity: 'EPIC',
    type: 'DRINK',
    author: 'Доби',
    points: 4,
  },
  {
    value: 'ПИЯН ПОП. Всеки да ти сипе по малко от неговия алкохол. Изпий го.',
    rarity: 'LEGENDARY',
    type: 'DRINK',
    author: undefined,
    points: 8,
  },
  //   NAUGHTY
  {
    value:
      'Дръж си ръката на гордостта за един рунд. Кожа в кожа. Дано не мирише...',
    rarity: 'COMMON',
    type: 'NAUGHTY',
    author: undefined,
    points: 1,
  },
  {
    value:
      'Изяш нещо страстно и съблазнително. Бананите, близалките, сливите и папаите са с предмиство.',
    rarity: 'UNCOMMON',
    type: 'NAUGHTY',
    author: undefined,
    points: 2,
  },
  {
    value: 'Лази по земята към {{randomPlayer}}, но секси.',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 3,
  },
  {
    value: 'Стой по бельо за един рунд.',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 4,
  },
  {
    value: 'Върти бутилката! Знаеш какво да правиш!',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 3,
  },
  {
    value:
      'Направи обратен стриптийз. Вместо да се събличаш, облечи възможно най-много дрехи и танцувай неловко.',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 2,
  },
  {
    value: 'Целувай се с ръката си. Страстно!',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 3,
  },
  {
    value: 'Целуни ръката на {{randomPlayer}}. Дланта.',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 3,
  },
  {
    value: 'Трябва да оближеш нещо от пръста на {{randomPlayer}}.',
    rarity: 'RARE',
    type: 'NAUGHTY',
    author: undefined,
    points: 3,
  },
  {
    value: 'Хвани бедрото на човека в дясно. Щипни го и го дръж един рунд.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Махни си бельото, но стой с долнище. Ако си само по бельо - стой по хавлия.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value: 'Целуни корема на {{randomPlayer}}.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value: 'Целуни страстно {{randomPlayer}} по бузата.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 4,
  },
  {
    value: 'Нека всички те поставят в засрамващи пози и да те снимат.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value: 'Нека всички те поставят в засрамващи пози и да те снимат.',
    rarity: 'EPIC',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Направи си голо селфи и го изпрати на своя партньор по каквото ти избереш. Ако нямаш партньор направи бял камък.',
    rarity: 'LEGENDARY',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value:
      'Другите играчи да застанат на произволни места. Завъжи си очите и търси някого в стаята. Целуни някъде първия, който хванеш без да си сваляш превръзката.',
    rarity: 'LEGENDARY',
    type: 'NAUGHTY',
    author: undefined,
    points: 5,
  },
  {
    value: 'Свали 3 дрехи по избор от себе си.',
    rarity: 'LEGENDARY',
    type: 'NAUGHTY',
    author: 'Доби',
    points: 5,
  },
  {
    value: 'Направи стриптийз и свали 2 дрехи от себе си.',
    rarity: 'LEGENDARY',
    type: 'NAUGHTY',
    author: 'Доби',
    points: 7,
  },
  {
    value:
      'Направи 7 минути в рая с партньора си. Не се пестете! Ако нямаш партньор, хъмпвай възглавница за 30 секунди!',
    rarity: 'LEGENDARY',
    type: 'NAUGHTY',
    author: 'Доби',
    points: 7,
  },
]

const COPY = {
  value: '',
  rarity: '',
  type: '',
  count: 1,
  author: undefined,
  points: 1,
}

export const DEFAULT_DECK = new Deck({
  cards: DECK.map((options) => new Card(options)),
  drawnIds: [],
  selectedCardId: null,
})
